/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./404.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f1f3ff",
        "surface-dark": "#111722",
        "outline-variant": "#c3c6d7",
        "on-surface": "#0B1220",
        "error": "#ba1a1a",
        "border-dark": "#293243",
        "surface-container-highest": "#dce2f6",
        "tertiary": "#00632b",
        "inverse-surface": "#2a3040",
        "outline": "#737686",
        "elevated-light": "#F9FBFD",
        "surface-container-lowest": "#ffffff",
        "soft-teal-fill": "#E8F7F4",
        "page-bg-dark": "#090D14",
        "text-muted-light": "#7C8798",
        "surface-container": "#e9edff",
        "text-primary-dark": "#F3F6FA",
        "primary-dark": "#60A5FA",
        "surface-variant": "#dce2f6",
        "border-light": "#DCE3EC",
        "page-bg-light": "#F6F8FC",
        "surface": "#f9f9ff",
        "on-primary": "#ffffff",
        "primary-container": "#2563eb",
        "soft-blue-fill": "#EAF1FF",
        "secondary": "#0F766E",
        "elevated-dark": "#171F2C",
        "secondary-dark": "#2DD4BF",
        "surface-bright": "#f9f9ff",
        "text-secondary-light": "#5B6678",
        "on-surface-variant": "#434655",
        "surface-light": "#FFFFFF",
        "primary": "#2563eb",
        "text-secondary-dark": "#9BA7B8",
        "on-error": "#ffffff",
        "surface-container-high": "#e2e8fc",
        "on-background": "#151b2a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "section-v-mobile": "48px",
        "section-v-desktop": "72px",
        "card-padding-sm": "24px",
        "baseline": "8px",
        "container-max": "1240px",
        "card-padding-lg": "32px",
        "gutter-desktop": "24px",
        "gutter-mobile": "18px",
      },
      fontFamily: {
        "headline-card": ["Manrope", "sans-serif"],
        "headline-section": ["Manrope", "sans-serif"],
        "label-technical": ["IBM Plex Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "hero-lg": ["Manrope", "sans-serif"],
        "headline-page": ["Manrope", "sans-serif"],
        "body-base": ["Inter", "sans-serif"],
      },
      maxWidth: {
        "container-max": "1240px",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
